
//functions used outside of dom modules
//setupGame,
//switchCurrentPlayer,
// switchTurn,
//setup,
// run,
// toggleBoardListeners,
//gameResult,
//endGame,
//playAgain,
// addPoint,
//getIndexAttributes,
//allShipsPlaced,
//getPlayerShips,
//confirmShips,
//  disableSetup,
//getCell,
